### PR TITLE
Add --only option

### PR DESCRIPTION
**Pull request by gilesknap**
Adds a command line option `--only` to specify which tags/branches to build. This is intended to maintain performance of CI as more tags are added to the repo. See example usage in this project: https://github.com/PandABlocks/PandABlocks-client. I added this because PandaBlocks-client documentation takes a little while to build.

I also added 

- documentation for `--only` argument
- documentation for usage with github actions deploying to github pages
- logging level control from command line `--log-level`

### CODE REVIEW

**Comment by Holzhaus** [comment]
The reason why it rebuilds all branches/tags is because the cross-version links need to be updated when adding a new version.

Have a look at https://manual.mixxx.org/2.2/en/ and check the "Other Versions" section at the bottom of the sidebar. If you add a new version but only build that particular version, there won't be a link to it when browsing older versions.

I think we could still to add a feature like you suggested in case the user doesn't add a list of other versions to the HTML template, but in that case you could also just use sphinx-build directly. Or am I missing something?

**Comment by gilesknap** [comment]
Hi, thanks for the fast response.

The way I'm using this is that I only update gh-pages with the changes, I don't delete any existing folders at commit time. Thus although we only build a subset of the versions, the old versions are still there.

This means that the cross version links only point to older versions and to master. I find this acceptable, you can always find the latest and all previous versions at the default link of master, from any tagged version you get links to earlier versions (and master).

I've just realised that my project currently does not show this because older documentation builds predate the change I made to your project. I'll fix this and send you a link so you can see what I'm describing.

**Comment by gilesknap** [comment]
There is an additional subtlety which is that when you check in a tag you typically kick off two CI workflows, one for master and one for the tag. Thus master is always updated to include all tags. (I am assuming here that all tags are pushed with master - but you can change the whitelist settings for this to work with other branches if required).

**Comment by gilesknap** [comment]
Hello again.

Trying to repair my historical documentation has convinced me that always only building documentation for the current commit is not a good approach. 

However I would still propose to support the --only option and use it as follows:

- for master branch un-tagged commits do a fast documentation build using --only master
- for tagged builds accept that a release takes longer and rebuild all versions of the documentation

This means that all versions will always include links to all other versions since all tags should predate the head of master.

If you think this is worthwhile, I'll update the documentation changes to describe this approach.

**Comment by gilesknap** [comment]
Another point has come to mind. 

With sphinx-multiversion we are always building all versions of the documentation with the latest templates and a single version of sphinx. Is it possible that breaking changes may stop the build from working because historical files are no longer compatible? 

If this is a risk then the approach of only building the current commit would get around this at the expense of never having forward links in historical documentation versions.

**Comment by gilesknap** [comment]
@Holzhaus I have fixed up the documentation pages on my project as an example of what I'm trying to achieve with this PR.
see https://pandablocks.github.io/PandABlocks-client

You can see master, current and **previous** version links from any version.

Note that in version 0.1.2 I made a template change to invert the order of version links. This change does not show in the earlier version 0.1.1 which  continues to look as it did when originally built. (This is not a breaking change, but if it was then it would not affect existing versions).

You can always navigate to future versions by first clicking on master.

So this PR has the following pros:

- faster builds for complex documentation
- preserves the look of historical documentation even when template changes were made in the future
- is safe against breaking changes in templates/sphinx/sphinx-multiversion

And the cons are:
- does not show links to future versions in historical versions

**Comment by gilesknap** [comment]
I'm closing this. I have a new approach to providing faster builds and will do a new PR._

**Pull request closed without merging**
