### PR TITLE
Allow variable substitution in command line defines

### PR DESCRIPTION
**Pull request by Holzhaus**
Attempt to fix edge cases where other extensions need to know about the
actual source path.

Resolves: #4

### CODE REVIEW

**Comment by Holzhaus** [comment]
@floriantschopp Please check if exhale works if you override the `containmentFolder` variable with `-D 'containmentFolder=${sourcedir}/api'`.

**Comment by floriantschopp** [comment]
@Holzhaus Thank you for taking care of this. I just tried it with 
```
sphinx-multiversion docs build/html -D 'containmentFolder=${sourcedir}/api'
```
with the following output
```
unknown config value 'containmentFolder' in override, ignoring
Failed load config for refs/heads/develop from /tmp/tmpgsg2thm0/0b7a48b9813033e54a78ae157ba9ed43629f084f/docs
unknown config value 'containmentFolder' in override, ignoring
unknown config value 'containmentFolder' in override, ignoring
Failed load config for refs/tags/initial_release from /tmp/tmpgsg2thm0/63ea0c8acb669904a711817b3cb74e314ecffec7/docs
Failed load config for refs/heads/master from /tmp/tmpgsg2thm0/618a0e0154d0c6e6cd84b5ac827140b5a9b84cb0/docs
Running Sphinx v2.4.4
/home/spadmin/.local/lib/python3.6/site-packages/sphinx/util/docutils.py:287: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
WARNING: unknown config value 'containmentFolder' in override, ignoring
WARNING: The config value `html_sidebars' has type `list', defaults to `dict'.

Configuration error:
The given `containmentFolder` [/home/spadmin/tmp/maplab_ws/src/maplab_experimental/maplab/docs/api] must be a *SUBDIRECTORY* of [/tmp/tmpgsg2thm0/ee893da17b9dc123dc1b4faa9f5b23a9ad3fc539/docs].
```

FYI: My `conf.py` is the following:
```python
import os

name = 'maplab'

on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_logo = "logo.png"

#source_parsers = {
#    '.md': 'recommonmark.parser.CommonMarkParser',
#}


extensions = [
    'breathe', 'exhale', 'sphinx.ext.autosectionlabel', 'recommonmark', 'sphinx_multiversion',
]

project = name
master_doc = 'index'

html_theme_options = {
    'canonical_url': 'maplab.asl.ethz.ch',
    'analytics_id': 'UA-XXXXXXX-1',  #  Provided by Google in your dashboard
    'logo_only': True,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'vcs_pageview_mode': 'edit',
    'style_nav_header_background': 'black',
    # Toc options
    # 'collapse_navigation': True,
    # 'sticky_navigation': True,
    # 'navigation_depth': 4,
    # 'includehidden': True,
    # 'titles_only': False
}

html_context = {
    'display_github': True,
    'github_repo': 'maplab',
    'github_user': 'ethz-asl',
    'github_version': 'develop-docs',
    'conf_py_path': '/docs/',
}

templates_path = [
    "templates",
]

html_sidebars = [
    "versions.html",
]

# Setup the breathe extension
breathe_projects = {"project": "./doxyoutput/xml"}
breathe_default_project = "project"

# Setup the exhale extension
exhale_args = {
    "verboseBuild": False,
    "containmentFolder": "./api",
    "rootFileName": "library_root.rst",
    "rootFileTitle": "Library API",
    "doxygenStripFromPath": "..",
    "createTreeView": True,
    "exhaleExecutesDoxygen": True,
    "exhaleUseDoxyfile": True,
    "pageLevelConfigMeta": ":github_url: https://github.com/ethz-asl/" + name
}
source_suffix = ['.rst', '.md']

# Tell sphinx what the primary language being documented is.
primary_domain = 'cpp'

# Tell sphinx what the pygments highlight language should be.
highlight_language = 'cpp'
```

**Comment by Holzhaus** [comment]
ah ok, the containment folder is inside the exhale_args dict. I have no idea if sphinx allows overriding value inside a dict, but you could try to use `-D exhale_args.containmentFolder=${sourcedir}/api` instead.

**Comment by floriantschopp** [comment]
The override seems to work, but the variable seems to be unset:
```
$ sphinx-multiversion docs build/html -D exhale_args.containmentFolder=${sourcedir}/api
Failed load config for refs/heads/develop from /tmp/tmpk87gkyct/0b7a48b9813033e54a78ae157ba9ed43629f084f/docs
Failed load config for refs/tags/initial_release from /tmp/tmpk87gkyct/63ea0c8acb669904a711817b3cb74e314ecffec7/docs
Failed load config for refs/heads/master from /tmp/tmpk87gkyct/618a0e0154d0c6e6cd84b5ac827140b5a9b84cb0/docs
Running Sphinx v2.4.4
/home/spadmin/.local/lib/python3.6/site-packages/sphinx/util/docutils.py:287: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
WARNING: The config value `html_sidebars' has type `list', defaults to `dict'.

Configuration error:
The given `containmentFolder` [/api] must be a *SUBDIRECTORY* of [/tmp/tmpk87gkyct/ee893da17b9dc123dc1b4faa9f5b23a9ad3fc539/docs].
```

**Comment by Holzhaus** [comment]
@floriantschopp Thanks for testing. I added some patches. Can you retest, please? If it doesn't work, add `--dump-metadata` and check the value of the `sourcedir` key. Is it empty, too?

**Comment by Holzhaus** [comment]
> The override seems to work, but the variable seems to be unset:
> 
> ```
> $ sphinx-multiversion docs build/html -D exhale_args.containmentFolder=${sourcedir}/api
> ...
> ```

You need to use single quotes around the override! Otherwise your shell will think it's an environment variable and try to replace it before it's passed to sphinx-multiversion. When there is no environment variable `sourcedir`, it will just replace it with an empty string.

Use it like this:

    $ sphinx-multiversion docs build/html -D 'exhale_args.containmentFolder=${sourcedir}/api'

**Comment by floriantschopp** [comment]
Thank you very much for the fixes and explanations! Seems to work now :-)
Do you see an easy method to define (e.g. in a file in the repo) which branches/tags of the repo are included in sphinx-multiversion? We normally have lots of branches with some experimental stuff that we don't need to build a documentation for...

**Comment by Holzhaus** [comment]
> Thank you very much for the fixes and explanations! Seems to work now :-)

Great!

> Do you see an easy method to define (e.g. in a file in the repo) which branches/tags of the repo are included in sphinx-multiversion? We normally have lots of branches with some experimental stuff that we don't need to build a documentation for...

https://holzhaus.github.io/sphinx-multiversion/master/configuration.html#tag-branch-remote-whitelists

**Pull request merged**
