### PR TITLE
add config item smv_rebuild_tags

### PR DESCRIPTION
**Pull request by gilesknap**
This new option enables faster builds for those that have a large number of tags and large documentation.

To enable add this to conf.py

`smv_rebuild_tags = False`

If this flag is False (defaults to True) then we skip any pre-existing target folders for tags. All branches are always rebuilt since they are subject to change.

Note that this means that historical documentation will have no forward links to future documentation. It is recommended that master is added to the branch whitelist so that this is always linked from all versions and will include links back to historical versions.

### CODE REVIEW

**Comment by dmwyatt** [comment]
@Holzhaus It'd be great if you could review and merge or give feedback so it can get merged on this and the other outstanding PR's. I understand if you've got time limitations but maybe just let everyone know if you're ever going to merge anything or if we should start looking into other options.

Thanks!

**Comment by thomascobb** [comment]
For information, we have now moved away from this approach (and sphinx-multiversion in general) in favour of doing the version switching in javascript at runtime in a custom `layout.html`. An example of this is here: https://github.com/dls-controls/versiongit/blob/master/docs/_templates/layout.html

**Comment by fraimondo** [comment]
@Holzhaus: We are using this in two of our libraries, and it's indeed perfect for our needs. However, this project is now lacking maintenance. I understand that you might not have time to deal with this, so is it possible that you give other devs push access or pass the torch so this can be done?

I am now facing an issue with pip, as now dependencies on sphinx-multiversion need to be fixed to specific branches/repos rather than just `pip install sphinx-multiversion`.

I'll be more than happy to take care.

**Comment by gilesknap** [comment]
Came here to close this PR and realized there is recent interest. Unfortunately it does not look like this is going anywhere. For our own projects we have moved on as per Tom's comments above. For the latest on how we do multiple versions of python docs see https://github.com/DiamondLightSource/python-copier-template

**Pull request closed without merging**
